"""
"""

BILLING_LOCK_TIMEOUT = 5
WALLET_CACHE_EXPIRE = 300
SERVICE_CACHE_EXPIRE = 3600

BILLING_QUEUE_NAME = "billing.api.calls"
BILLING_EXCHANGE_NAME = "billing.exchange"
BILLING_ROUTING_KEY = "api.call.billing"

BILLING_RETRY_TIMES = 3
BILLING_BATCH_SIZE = 100

ENABLE_BILLING = True
