KEY_PLATFORM_NAME = "platform_name"
KEY_PLATFORM_LOGO = "platform_logo"
KEY_PLATFORM_URL = "platform_url"
KEY_WEBSITE_TITLE = "website_title"
KEY_HEADLINE = "headline"
KEY_SUBHEADLINE = "subheadline"
KEY_LANGUAGE = "language"
KEY_THEME = "theme"
KEY_ABOUT_PAGE = "about_page"
KEY_ADMIN_USERNAME = "admin_username"
KEY_ADMIN_PASSWORD = "admin_password"
KEY_LOGIN_GOOGLE_CLIENT = "login_google_client_id"
KEY_LOGIN_GOOGLE_SECRET = "login_google_client_secret" 
KEY_LOGIN_GOOGLE_REDIRECT_URI = "login_google_redirect_uri"
KEY_LOGIN_GOOGLE_ENABLE = "login_google_enable"
KEY_EMAIL_SMTP_HOST = "email_smtp_host"
KEY_EMAIL_SMTP_PORT = "email_smtp_port"
KEY_EMAIL_SMTP_USER = "email_smtp_user"
KEY_EMAIL_SMTP_PASSWORD = "email_smtp_password"
KEY_EMAIL_SMTP_SENDER = "email_smtp_sender"
KEY_LOGIN_EMAIL_ENABLE = "login_email_enable"
KEY_LOGIN_EMAIL_MODE = "login_email_mode"
KEY_DOMAIN = "domain"
KEY_IS_SHOWCASED = "is_showcased"
KEY_MCP_SERVER_PREFIX = "mcp_server_prefix"

KEY_FAQ = "faq"
KEY_TOP_NAVIGATION = "top_navigation"
KEY_EMBEDED_HTML = "embedded_html"

KEY_META_DESCRIPTION = "meta_description"

KEY_X_TITLE = "x_title"
KEY_X_DESCRIPTION = "x_description"
KEY_X_IMAGE_URL = "x_image_url"

KEY_FACEBOOK_TITLE = "facebook_title"
KEY_FACEBOOK_DESCRIPTION = "facebook_description"
KEY_FACEBOOK_IMAGE_URL = "facebook_image_url"

KEY_SOCIAL_ACCOUNT_FACEBOOK_URL = "social_account_facebook_url"
KEY_SOCIAL_ACCOUNT_X_URL = "social_account_x_url"

KEY_CNAME_A_IP = "cname_a_ip"

KEY_DEFAULT_RESOURCE_GROUP = "default_resource_group"